import { Post, Comment } from "./types";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000);

export const mockPosts: Post[] = [
  {
    id: "1",
    title: "I still think about her every single day",
    content: "It's been 6 months since we broke up and I can't stop replaying our conversations. We had the same classes and now I avoid the library just so I don't run into her. Is this normal? Does it ever stop hurting?",
    authorAlias: "Anonymous#4821",
    category: "love",
    upvotes: 147,
    downvotes: 3,
    commentCount: 23,
    createdAt: hoursAgo(2),
  },
  {
    id: "2",
    content: "Failed my midterm for the third time. My parents think I'm doing great. I don't know how much longer I can keep pretending. The pressure is crushing me and I have no one to talk to about it.",
    authorAlias: "Anonymous#7193",
    category: "mental-health",
    upvotes: 234,
    downvotes: 1,
    commentCount: 45,
    createdAt: hoursAgo(5),
  },
  {
    id: "3",
    title: "Hot take: 8am lectures should be illegal",
    content: "Who decided that making sleep-deprived college students attend lectures at 8am was a good idea? I've missed more 8am classes than I've attended and my GPA is proof.",
    authorAlias: "Anonymous#2056",
    category: "rant",
    upvotes: 89,
    downvotes: 12,
    commentCount: 31,
    createdAt: hoursAgo(8),
  },
  {
    id: "4",
    title: "How do you actually make friends in college?",
    content: "I'm a sophomore and I still eat lunch alone most days. Everyone seems to already have their friend groups. Any advice from someone who figured it out?",
    authorAlias: "Anonymous#5534",
    category: "advice",
    upvotes: 198,
    downvotes: 2,
    commentCount: 67,
    createdAt: hoursAgo(12),
  },
  {
    id: "5",
    content: "Just want to say that the person who leaves motivational sticky notes in the study rooms — you've gotten me through finals week more than once. Thank you, whoever you are. 💛",
    authorAlias: "Anonymous#8910",
    category: "general",
    upvotes: 312,
    downvotes: 0,
    commentCount: 18,
    createdAt: hoursAgo(1),
  },
  {
    id: "6",
    title: "Study group for Organic Chemistry?",
    content: "Looking for people who are struggling with OChem as much as I am. Maybe we can fail together... or actually learn something. DM me if interested (jk this is anonymous lol).",
    authorAlias: "Anonymous#3347",
    category: "study",
    upvotes: 56,
    downvotes: 4,
    commentCount: 12,
    createdAt: hoursAgo(18),
  },
];

export const mockComments: Comment[] = [
  {
    id: "c1",
    postId: "1",
    content: "Bro, it takes time. I was in the same boat last year. It gets better, I promise. Focus on yourself.",
    authorAlias: "Anonymous#6612",
    upvotes: 34,
    downvotes: 0,
    createdAt: hoursAgo(1.5),
  },
  {
    id: "c2",
    postId: "1",
    content: "6 months is nothing. Give yourself grace. Healing isn't linear.",
    authorAlias: "Anonymous#1198",
    upvotes: 28,
    downvotes: 1,
    createdAt: hoursAgo(1),
  },
  {
    id: "c3",
    postId: "2",
    content: "Please talk to a counselor. The campus mental health center is free and they really do help. You're not alone in this.",
    authorAlias: "Anonymous#4420",
    upvotes: 89,
    downvotes: 0,
    createdAt: hoursAgo(4),
  },
  {
    id: "c4",
    postId: "4",
    content: "Join clubs! Seriously. I joined the hiking club just for fun and met my best friends there.",
    authorAlias: "Anonymous#7782",
    upvotes: 45,
    downvotes: 2,
    createdAt: hoursAgo(10),
  },
];
